backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Project Title", widget: "string" }
      - { name: "status", label: "Status", widget: "string" }
      - { name: "about", label: "About", widget: "text" }
      - { name: "items", label: "Items", widget: "list" }
      - { name: "build_log", label: "Build Log", widget: "markdown" }
      - { name: "photos", label: "Photos", widget: "image" }
